### ISSUE TITLE
 the time of process one epoch

### ISSUE THREAD

**Issue by noronet** [nl8590687/ASRT_SpeechRecognition#80]
hello dear
i have processed your code in GPU 1070Ti and RAM32
i was forced set batch_size=12 because my system not handle batch_size=>16
i would want how many times process of one epoch?
i have trained model in 20hours
and get model name "speech_model251_e_0_step_122000.model" but one epoch not complete yet.
my data-number is 110000 and my step save is 500. 
what value of **n_step** until 1-epoch is complete?

**Comment by nl8590687** [comment]
Regarding the first question, the batch size cannot be set to 16 because the GPU has insufficient storage space. Please use a larger memory gpu.
Regarding the epoch problem, it is because I am using the random sampling method. There is no strict epoch boundary. The epoch value is always 1, so you only need to see how many times the data is iterated.
hope it can help you.

**Comment by noronet** [comment]
very very thanks for reply this question .
